Repository SirSerje/bootcamp-simple, pull requests merged in 2019-04, with the labels that each got.

#24 fix problem with lint
  app/utils/request.js
  assets/styles/index.css
  yarn.lock
Labels: js, lint

#16 #10 setup tests with Jest. Add test for dateConverter
  app/__tests__/dateConverter.test.js
  babel.config.js
  package.json
Labels: js, setup

#27 changed sync code to async task#9
  .eslintrc.json
  app/__tests__/dateConverter.test.js
  app/index.js
  app/utils/dateConverter.js
  app/utils/request.js
Labels: js

#30 #29 add responseParser test, add mock for request()
  app/__tests__/responseParser.test.js
  app/mock/apiResponseMock.js
  app/utils/request.js
Labels: js

#28 #8 JSON.parse - error
  app/__tests__/dateConverter.test.js
  app/__tests__/responseParser.test.js
  app/index.js
  app/mock/apiResponseMock.js
  app/responseParser.js
  app/utils/dateConverter.js
  app/utils/request.js
Labels: js

#25 5 add date converter
  .travis.yml
  app/__tests__/dateConverter.test.js
  app/utils/dateConverter.js
Labels: js
